apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 450215408596.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 450215408596.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e55b0575
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
